### ISSUE TITLE
Adding support for dataframe will be very useful

### ISSUE THREAD

**Issue by Lewis-Liu** [korsbo/Latexify.jl#111]
[DataFrames](https://github.com/JuliaData/DataFrames.jl) is very useful in Julia.  
The header and content in the DataFrame object correspond to the header and content in the LaTex table.

**Comment by Lewis-Liu** [comment]
From the site https://korsbo.github.io/Latexify.jl/stable/, I have known that Latexify supports Dataframe.

**Comment by korsbo** [comment]
Thanks for the suggestion and for pointing out the faults in the documentation! Latexify.jl has been a bit neglected of late but I'm hopeful that I can resume at least a normal level of maintenance in two months or so - after I have submitted my dissertation.

**Comment by Lewis-Liu** [comment]
Thank you very much for your work. @korsbo
