### ISSUE TITLE
WARNING: Method definition overwritten

### ISSUE THREAD

**Issue by Hieronimo** [korsbo/Latexify.jl#128]
I get this warning:
```julia
WARNING: Method definition latexraw(Base.Missing) in module Latexify at ..../.julia/packages/Latexify/20peP/src/latexraw.jl:136 overwritten at ..../.julia/packages/Latexify/20peP/src/plugins/Missings.jl:3.
```

**Julia Version 1.4.1
[23fbe1c1] Latexify v0.14.5**

**Comment by korsbo** [comment]
Thanks for reporting! It seems I'm defining the same method twice. The definitions are identical so it this mistake does not have any effect but it should be fixed nevertheless.
