### ISSUE TITLE
Are kwargs preferable over having multiple functions exported?

### ISSUE THREAD

**Issue by korsbo** [korsbo/Latexify.jl#13]
Currently Latexify.jl presents one function for each kind of output (inline, array, align, etc), as well as one function (`latexify`) which tries to infer the preferred output. An alternative to this would be to just have one function to which you can pass a kwarg to specify what latex environment you want to output. 
For example, `latexalign(x)` could be replaced by `latexify(x; env=:align)`. `latexify` could still use clever defaults which depends on the input type, but allow the user to override this. 

The difference would be rather minimal, but I'm wondering if this would be more natural/easier to remember. 

Any input would be appreciated.

**Comment by ChrisRackauckas** [comment]
Yeah I think it's a good idea.

**Comment by goropikari** [comment]
I also agree.
In addition, if we can change default environment as by Maxima's `set_tex_environment_default`, it is more useful.
http://maxima.sourceforge.net/docs/manual/maxima_13.html#SEC74

**Comment by korsbo** [comment]
This is now implemented and awaiting a release. I'm closing the issue.

However, I have not implemented a way for the user to change the default environment as per @goropikari's suggestion.

Currently it would be possible to overload 
```julia
import Latexify: get_latex_function
Latexify.get_latex_function(arg::MyArrayType) = Latexify.latexarray
```
This should have the intended effect, but it is a little bit clumsy. 

If this remains a nuisance, open an issue and I will look in to it after the Julia 1.0 version is up and running.
