### ISSUE TITLE
Support rendering PNG files

### ISSUE THREAD

**Issue by schneiderfelipe** [korsbo/Latexify.jl#132]
Hi @korsbo,

The [`render` function](https://github.com/korsbo/Latexify.jl/blob/005020d96d11cb57b4fcc97549eed69dfe479c11/src/utils.jl#L15) is very useful, but I wonder if it could be improved by supporting PNG output as well. `matplotlib.texmanager` does that by using `dvipng` (see code [here](https://github.com/matplotlib/matplotlib/blob/99e6240d95e86b4fd9edbcbefa8a5a135e707f27/lib/matplotlib/texmanager.py#L271) and [here](https://github.com/matplotlib/matplotlib/blob/99e6240d95e86b4fd9edbcbefa8a5a135e707f27/lib/matplotlib/texmanager.py#L332)).

Do you think it is a useful addition? I could try to make a PR.

**Comment by korsbo** [comment]
Sure, that'd be good, thanks!
