### ISSUE TITLE
Improper treatment of exponents with negative base

### ISSUE THREAD

**Issue by Luapulu** [korsbo/Latexify.jl#142]
I get

```julia
julia> latexify("(-1)^2")
L"$-1^{2}$"
```

However, `- 1^2 != (-1)^2`.

**Comment by korsbo** [comment]
Thanks for reporting! 

The same bug also seems to cause errors to other exponents where the first argument is not an expression, like `latexify(:($(1+2im)^2))` or with `Rational`s.
