### ISSUE TITLE
latexifymerge

### ISSUE THREAD

**Issue by gustaphe** [korsbo/Latexify.jl#144]
https://github.com/korsbo/Latexify.jl/blob/36f88564dffe40005fefa68cdaae9b0135a73812/src/latexoperation.jl#L16-L18

Is this intended for recipes to be able to return a series of arguments whose latexifications are just concatenated? If so, that's very useful functionality, but then there's a bug. If not, I would like to request such functionality.

It seems the other uses of `latexoperation()` return `String`s, but this one returns a `Symbol`, so 
```julia
julia> latexify(Expr(:latexifymerge,3,"cm"))
ERROR: MethodError: no method matching unicode2latex(::Symbol)
```

Simply removing the `Symbol()` at L18 seems to fix this, but I'm not completely confident this is what that function is supposed to do.

**Comment by korsbo** [comment]
You're right. It is intended to allow for easy joining of things. Is should probably be `join(args)` though.
