### ISSUE TITLE
Problems with ' character in markdown conversion

### ISSUE THREAD

**Issue by Datseris** [korsbo/Latexify.jl#15]
Hi!
```julia
d = DataFrame(A = 1:4, B = ["A's blues", "B", "C", "D"],  
C = ["x/y", "x_subscript", "gamma(x)", 1//2])

4×3 DataFrames.DataFrame
│ Row │ A │ B         │ C           │
├─────┼───┼───────────┼─────────────┤
│ 1   │ 1 │ A's blues │ x/y         │
│ 2   │ 2 │ B         │ x_subscript │
│ 3   │ 3 │ C         │ gamma(x)    │
│ 4   │ 4 │ D         │ 1//2        │
```
but
```
md(d)
```
```
ParseError("extra token \"blues\" after end of expression")
#parse#234(::Bool, ::Bool, ::Function, ::String, ::Int64) at parse.jl:222
(::Base.#kw##parse)(::Array{Any,1}, ::Base.#parse, ::String, ::Int64) at <missing>:0
#parse#235(::Bool, ::Function, ::String) at parse.jl:232
latexinline(::String) at latexinline.jl:2
collect_to!(::Array{LaTeXStrings.LaTeXString,2}, ::Base.Generator{Array{Any,2},Latexify.#latexinline}, ::Int64, ::Int64) at array.jl:508
collect(::Base.Generator{Array{Any,2},Latexify.#latexinline}) at array.jl:476
#mdtable#151(::Bool, ::Array{Symbol,1}, ::Array{Any,1}, ::Bool, ::Function, ::Array{Any,2}) at mdtable.jl:60
(::Latexify.#kw##mdtable)(::Array{Any,1}, ::Latexify.#mdtable, ::Array{Any,2}) at <missing>:0
#mdtable#168(::Array{Any,1}, ::Function, ::DataFrames.DataFrame) at mdtable.jl:85
mdtable(::DataFrames.DataFrame) at mdtable.jl:85
#md#120(::Symbol, ::Array{Any,1}, ::Function, ::DataFrames.DataFrame, ::Vararg{DataFrames.DataFrame,N} where N) at md.jl:6
md(::DataFrames.DataFrame, ::Vararg{DataFrames.DataFrame,N} where N) at md.jl:4
include_string(::String, ::String) at loading.jl:522
eval(::Module, ::Any) at boot.jl:235
(::Atom.##119#122)() at eval.jl:148
withpath(::Atom.##119#122, ::Void) at utils.jl:30
withpath(::Function, ::Void) at eval.jl:38
macro expansion at eval.jl:147 [inlined]
(::Atom.##118#121{Dict{String,Any}})() at task.jl:80
```

**Comment by korsbo** [comment]
Thanks for reporting!

This seems to be a problem with all of latexify. `Base.parse(some_string)` is called, and if you pass a ` character it parses that as an operation. Latexify currently does not know how to deal with that operation. I could define what it should do when it encounters that operation, but I'm not sure what the default should be. 

For your immediate problem
```julia
md(d; latex=false)
```
may be helpful. 

A better fix may be a little tricky,

`parse("hello")` gives a symbol `:hello`, but `parse("A's")` gives an expression which essentially becomes:

```julia
*( '(:A), :s)
``` 
It would be easy to tell latexify to interpret this as `"A's"`, but that would cause strange behaviour when parsing maths in strings `latexify("x' * 2x")`.

I'll have to think some more on this.

**Comment by Datseris** [comment]
Thank you @korsbo , using `md(d; latex = false)` did the trick. I didn't want Latex anyway, so I am waiting for the documentation

**Comment by korsbo** [comment]
I'm happy to help. 

I don't know how to fix the underlying problem of automatic inference of whether a string should be parsed as maths or not. My conclusion at the moment is that Latexify should not even attempt this. I have however added a less cryptic error message which tells you what is wrong and suggests a way to bypass it.
