### ISSUE TITLE
latexarray fails with single-element arrays

### ISSUE THREAD

**Issue by korsbo** [korsbo/Latexify.jl#164]
`latexify(:(x = [1.]))` errors.

**Comment by gustaphe** [comment]
That's bizarre. 

```julia
:([1.]).head === :([1., 2.]).head === :vect
latexify(:(x = $([1.]))) # works
```

A hack would be to create a `_latexarray(::Any)`, but there is probably something weird going on behind the scenes.

**Comment by korsbo** [comment]
`reduce(hcat, [1])` returns a different type than `reduce(hcat, [1,1])`... This messes up `expr_to_array`.

**Comment by korsbo** [comment]
Ickie. This means that other single-element things will also fail. I have `reduce(hcat, x)` all over the place. What I really want is `hcat(x...)` but that is not great for the compiler to work with.

`latexify([:x], env=:table)`
