### ISSUE TITLE
latexify(-Inf) ignores the -

### ISSUE THREAD

**Issue by jessebett** [korsbo/Latexify.jl#174]
```
julia> using Latexify

julia> latexify(Inf)
L"$\infty$"

julia> latexify(-Inf)
L"$\infty$"
```

![Screen Shot 2021-05-26 at 10 27 36 PM](https://user-images.githubusercontent.com/4240549/119756785-fa02c700-be71-11eb-8733-887097453c79.png)

**Comment by korsbo** [comment]
Fixed in v0.15.6
