### ISSUE TITLE
Text alignment ("adjustment") not working for `:mdtable` environment.

### ISSUE THREAD

**Issue by kapple19** [korsbo/Latexify.jl#178]
Works fine for tabular and other environments though.

![image](https://user-images.githubusercontent.com/48305293/125577299-1f08f6b6-1b5f-49b6-873b-5968569ee230.png)

I cannot just convert to string, move the `:` positions, then convert back to Markdown.MD, since such processing loses the markdown newline, and doesn't escape the `\n`s.

**Comment by gustaphe** [comment]
Closed in #218
