### ISSUE TITLE
Latexify(?) messes up julia `help` output

### ISSUE THREAD

**Issue by lamorton** [korsbo/Latexify.jl#181]
I'm not totally sure what I did exactly to precipitate this b/c I'm having trouble getting it to reproduce, but it's not the first time it's happened when I've been using Latexify to look at ModelingToolkit equations, and it hadn't been happening prior to that in the session, nor in other sessions in the same project in which I didn't use Latexify.  Basically, the `?` help prompt gets borked like this:

<img width="1494" alt="Screen Shot 2021-08-07 at 6 08 11 PM" src="https://user-images.githubusercontent.com/23484003/128617738-c5ddc083-6e4f-40a0-8267-093b3a5a91dd.png">

Packages potentially involved:
```julia
using DifferentialEquations, Plots, DiffEqFlux, Unitful, AxisArrays, HDF5, DataInterpolations, GridInterpolations, GalacticOptim, ModelingToolkit, Zygote, BlackBoxOptim, IfElse

(Julia) pkg> st
      Status `~/Code/Julia/Project.toml`
  [39de3d68] AxisArrays v0.4.4
  [a134a8b2] BlackBoxOptim v0.6.0
  [82cc6244] DataInterpolations v3.6.0
  [aae7a2af] DiffEqFlux v1.42.0
  [0c46a032] DifferentialEquations v6.18.0
  [587475ba] Flux v0.12.6
  [f6369f11] ForwardDiff v0.10.19
  [a75be94c] GalacticOptim v2.0.3
  [bb4c363b] GridInterpolations v1.1.2
  [f67ccb44] HDF5 v0.15.6
  [615f187c] IfElse v0.1.0
  [b964fa9f] LaTeXStrings v1.2.1
  [2ee39098] LabelledArrays v1.6.3
  [23fbe1c1] Latexify v0.15.6
  [961ee093] ModelingToolkit v5.26.0 `~/Code/Jdev/ModelingToolkit`
  [8913a72c] NonlinearSolve v0.3.8
  [429524aa] Optim v1.4.1
  [1dea7af3] OrdinaryDiffEq v5.60.2
  [a03496cd] PlotlyBase v0.8.4
  [91a5bcdd] Plots v1.19.4
  [438e738f] PyCall v1.92.3
  [d330b81b] PyPlot v2.9.0
  [0bca4576] SciMLBase v1.18.2
  [0c5d862f] Symbolics v1.4.2
  [1986cc42] Unitful v1.9.0
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
```

I'm working in VSCode 1.59 FWIW. I also have in my `startup.jl`
```julia
using Pkg
using Revise
using Debugger
using AbstractTrees
```

**Comment by korsbo** [comment]
huh, that is super wierd. Is the `?` prompt borked for functions that do not exist in Latexify as well? `md` is pulled in from `Markdown`, so `Latexify.md` does exist even if I don't think I created any `md` functions myself.

**Comment by lamorton** [comment]
I posted this on Julialang as well & they said it was probably a known bug with Revise & closed it. I forgot I had this open.
