### ISSUE TITLE
How to display SDE system for Catalyst reaction networks?

### ISSUE THREAD

**Issue by TorkelE** [korsbo/Latexify.jl#196]
Is there currently a way to do this? The documentation refers
```julia
latexify(rn; noise=true)
```
but I believe that this is the old DiffEqBiological notation, from before we based everything on ModelingToolkit? Is there a way to do it currently?

**Comment by korsbo** [comment]
Yeah, that seems like some very old syntax. I would think that something like `latexify(convert(SDESystem, rn))` might work. Whether it does, however, would really be up to the latexify recipe in ModelingToolkit though.

**Comment by TorkelE** [comment]
Good point, yeah, it probably belongs there.
