### ISSUE TITLE
Latexification of numbers in scientific notation gives misleading results

### ISSUE THREAD

**Issue by david-macmahon** [korsbo/Latexify.jl#199]
`latexify(1/100000)` is rendered as `1.0e - 5`, which looks like a subtraction expression, rather than something more readable like `1x10^{-5}`.

**Comment by gustaphe** [comment]
```
1\mathrm{e}{-10}
```

would be an initial option.

**Comment by david-macmahon** [comment]
Never mind.  I just found out about `FancyNumberFormatter` 🙄.  Sorry for the noise.
