### ISSUE TITLE
Float numbers in scientific notation: `1e-6` renders like `L"$1.0e - 6$"`

### ISSUE THREAD

**Issue by adomasbaliuka** [korsbo/Latexify.jl#203]
Currently, floating point numbers that correspond to scientific notation with large exponents are rendered in a way that may be confusing to readers of the rendered equations.

The notation "1.2e6" may be "familiar enough" to people to not be misinterpreted, even though it is uncommon in a LaTeX context. However, when using negative exponents, `latexify(1e-6) === L"$1.0e-6$"`, really reads more like "(1.0e) - 6". Due to context (who ever subtracted 6 from Euler's number?), this isn't *likely* to be misinterpreted, but the added spaces really don't help and also eliminate the advantage of the abbreviation. For example, L"1.0 \times 10^{-6}" only takes about one additional character when rendered.

I propose that `L"1 \times 10^{-6}"` or `L"1 \cdot 10^{-6}"` should be the default LaTeX representation for `1e-6`.

**Comment by gustaphe** [comment]
This was partially solved in #201 , in that it now does this with `StyledNumberFormatter` or `FancyNumberFormatter`:

```julia
julia>using Pkg; Pkg.develop("Latexify");
julia>using Latexify

julia> latexify(1e6; fmt=FancyNumberFormatter())
L"$1 \cdot 10^{6}$"

julia> latexify(1e6; fmt=StyledNumberFormatter())
L"$1 \mathrm{e}{6}$"
```

Now whether that should be the default behaviour is up to debate I guess.

**Comment by adomasbaliuka** [comment]
Thanks a lot for your answer! I seem to have missed this bit about the formatter objects when I looked at the documentation, sorry about that.

By the way, was there any reason why you used `Pkg.develop` for your example?

**Comment by gustaphe** [comment]
> was there any reason why you used Pkg.develop for your example?

Yes, the improvements of #201 are currently only in `master`, not in a numbered release. for the specific case of `1e6` it works anyway, but for instance `1e-6` looks strange before that commit.
