### ISSUE TITLE
Symbolics and Latexify

### ISSUE THREAD

**Issue by qwertyjl** [korsbo/Latexify.jl#226]
I do not know if it is right to write these things here, if not I apologize.
1)The mathematical expressions in symbolics contain various false and true which are useful in calculations but which make reading difficult. For example:  
```julia
@variables y
latexify(im*y)  # false+yi
```
How can I avoid viewing them?

2)this does not work:
```julia
@syms k
latexify(k*im) # error
```
3)This output is unreadable:
```julia
@variables y
dy = Differential(y)
dy(dy(dy(dy(y))))
```
4)I think imaginary numbers could use an easily recognizable unicode character such as: ⅈ. In my opinion it would make formulas with complex numbers more readable.

**Comment by gustaphe** [comment]
I think these are issues in the `Symbolics.jl` latexrecipes, as it works well with `latexify(3im)`. Note that if this is made to work properly, there is a kwarg to change the imaginary unit symbol:

```julia
julia> latexify(3im)
L"$3\mathit{i}$"

julia> latexify(3im; imaginary_unit="ⅈ")
L"$3ⅈ$"
```

So report this at Symbolics and maybe ping me there, I'll be happy to take a look (but probably not today, as it seems I'll have to learn the difference between a var and a sym ...).

**Comment by gustaphe** [comment]
As pertains to your third question, I'm not sure I understand, because I don't get that output, and it's not related to `Latexify`.

```
julia> dy = Differential(y)
(::Differential) (generic function with 2 methods)

julia> dy(y)
Differential(y)(y)

julia> latexify(dy(y))
L"\begin{equation}
\mathrm{\frac{d}{d y}}\left( y \right)
\end{equation}
"
```
(I would probably want that to be `\mathrm{d}`, but that can be fixed)
