### ISSUE TITLE
"permille" symbol

### ISSUE THREAD

**Issue by ggebbie** [korsbo/Latexify.jl#233]
Issue: Pluto notebook doesn't render the LaTeX output of a variable with units of "permille". 

MWE in a Pluto notebook:

```
using Latexify, Unitful, UnitfulLatexify

δ = 0.5u"permille"

@latexdefine δ
```
Output in Pluto notebook (v0.19.13) is:
`\delta = 0.5\;\mathrm{\textnormal{\textperthousand}}`
highlighted in yellow.

Workaround: Use commented code on L530 of Latexify/src/unicode2latex.jl.  Essentially just use `\perthousand` as the LaTeX equivalent of the unicode "permille" character. 

This workaround may depend on the particular OS, etc. There must be some history with these lines that are commented out. If this workaround is a fix for the problem that is useful to others, I can make a PR.

**Comment by korsbo** [comment]
Are you using the latest latexify? the line you are referring to is not commented: https://github.com/korsbo/Latexify.jl/blob/feaa3ada85e69daea240d2c58422892e60e8d644/src/unicode2latex.jl#L530

**Comment by korsbo** [comment]
or you mean that it should just map to `raw"\perthousand"`?

**Comment by gustaphe** [comment]
I looked through the blame history, and it hasn't recently changed.

`\perthousand` is not defined in LaTeX, and `\textperthousand` comes from the `textcomp` package. Does `\perthousand` render right in Pluto?

**Comment by korsbo** [comment]
When it comes to rendering in editors and browser, maybe the best approach is to just not convert the unicode (`convert_unicode=false`).

**Comment by gustaphe** [comment]
I tested, and yes `L"$\perthousand$"` works in Pluto and Plots. Is there a prior policy when it comes to priorities, is it better that something renders right wrt these or that it produces correct TeX code? For anyone who tries to create correct TeX code it might anyway be better to use `using Unitful, UnitfulLatexify, Latexify; latexify(u"permille"; unitformat=:siunitx)` so...

**Comment by ggebbie** [comment]
Thanks a lot for checking this out and for the quick response.   Correct, if I map to `raw"\perthousand"`, then Pluto renders the symbol correctly. I will play with the suggestions regarding `convert_unicode=false` and `unitformat=:siunitx`.  

Side note about making correct TeX code: I usually use `\permil` from the package `wasysym` in my TeX files because it works in both text mode and math mode.

I'm impressed with the collection of packages for Julia and LaTeX; thanks to you both for your contributions.

**Comment by ggebbie** [comment]
Some experimentation:  the title of this should have been regarding the function `latexify` rather than the macro `@latexdefine` more specifically.

`latexify(δ,convert_unicode=false)` works in Pluto for me. Thanks!

`latexify(δ,unitformat=:siunitx`) returns `\qty0.5\permille`. (Perhaps I need additional code to render the LaTeX?)

In my other LaTeX files, I confirm that `\perthousand` doesn't work but `\textperthousand` does.

**Comment by gustaphe** [comment]
Yes, `siunitx` is a LaTeX package, absolutely essential. It won't work in MathJax (like Pluto), but if you're inputting things from Julia in a real LaTeX document, it's the best option.

**Comment by korsbo** [comment]
Ok, it sounds to me that the current way we're converting the permille sign is actually a reasonably good one even though some renderers can't handle it (no way to please every backend here). The solution for having things rendered nicely in Pluto, etc, is probably to just leave the unicode alone. Pluto and friends can typically handle that while LaTeX only can if you load some inputenc package or use LuaLaTeX or XeLaTeX. 

We do already have the option of doing `Latexify.set_default(; convert_unicode=false)` such that you don't need to pass `convert_unicode=false` in every latexify call in a notebook. 

Maybe for a next majorly breaking release, we should default to not converting unicode characters to LaTeX commands. That is starting to seem like the lesser of two evils to me.

**Comment by ggebbie** [comment]
Thanks for the help re: `siunitx` and the advice for setting the default to `convert_unicode=false`. It's nice to have these things recorded here. The state of the discussion makes sense to me; there are two competing use cases going on with good solutions for both. Sometimes there will need to be some intervention by the user.   (Feel free to close issue at your convenience.)

**Comment by gustaphe** [comment]
Yeah, even LaTeX itself is starting to accept unicode (I hear). This will also be more configurable in the big rework.
