### ISSUE TITLE
Missing infix operators for mathematics

### ISSUE THREAD

**Issue by joshniemela** [korsbo/Latexify.jl#246]
`latexify("a ∈ b")` results in `L"$\in\left( a, b \right)$"` and should probably return `L"$a \in b$"`.
`\forall` and `\exists` and probably other infix operators result in a crash.

**Comment by gustaphe** [comment]
Neither `\forall` nor `\exists` are infix in julia:
```
julia> Meta.isbinaryoperator.((:∀, :∃))
(false, false)
```
, but `\forall` could be implemented. Do you think `\exists` should be treated as infix? I can't recall ever seeing it used as such. And do you have other ideas for operators that should be infixed?

**Comment by joshniemela** [comment]
Yep you're right, exists isn't supposed to be infix but the others should be, I don't really have any operators in mind at the moment, maybe a lot of the logical operators if they don't already infix themselves.

**Comment by jakobjpeters** [comment]
My package wants to handle infix operators too, which is handled incorrectly.

**Comment by jakobjpeters** [comment]
I discovered that you need to wrap the string in a `Symbol`. This should be documented though.
```julia
julia> latexify(Symbol("a ∈ b"))
L"$a \in b$"
```

**Comment by gustaphe** [comment]
Could I ask you guys to try out #296 ? It's difficult to test if this works right, since it is partially taste.
Specifically, I want to know if parentheses work as you expect, and if there are any operators you miss.
