### ISSUE TITLE
SDESystem output is identical to ODESystem output

### ISSUE THREAD

**Issue by TorkelE** [korsbo/Latexify.jl#249]
Simple example:
```julia
using Catalyst
using Latexify
rn = @reaction_network begin 
    (p,d), 0 <--> X
    (kB,kD), 2X <--> X2
end 
latexify(convert(SDESystem, rn))
```
looks like the ODE system, e.g:
![image](https://user-images.githubusercontent.com/18099310/217045123-74311043-3806-4f63-804e-f6ada96dae43.png)
The noise terms are missing.

Nothing that need an urgent fix, but figured I should record it at least.

**Comment by ChrisRackauckas** [comment]
This is likely an MTK not a Latexify issue

**Comment by TorkelE** [comment]
Have moved issue to MTK: https://github.com/SciML/ModelingToolkit.jl/issues/2069
