### ISSUE TITLE
Unwrapped exponents with SymEngine

### ISSUE THREAD

**Issue by ThatcherC** [korsbo/Latexify.jl#270]
I'm seeing a weird issue where SymEngine expressions with exponents with decimal points don't get latexified correctly.

Running in Julia 1.9,
```
(@v1.9) pkg> status SymEngine Latexify
Status `~/.julia/environments/v1.9/Project.toml`
  [23fbe1c1] Latexify v0.16.1
  [123dc426] SymEngine v0.9.1

julia> using SymEngine, Latexify

julia> @vars a
(a,)

julia> latexify(a^0.5)
L"$a^0.5$"

julia> latexify(:(b ^ 0.4))
L"$b^{0.4}$"
```

Visually the two Latex outputs look like this:
![image](https://github.com/korsbo/Latexify.jl/assets/2112477/864947c9-babb-4e1c-9f94-2b2d52faa05c)

Clearly the `0.5` exponent in the `a^0.5` expression should have been rendered as `$a^{0.5}`, like the `b` expression was.

What's extra weird is that my SymEngine expression converts to the same Expr as the literal one I wrote above:

```
julia> @vars a
(a,)

julia> Meta.parse(string( a^0.5 ))
:(a ^ 0.5)
```

Any idea what's up? I've looked through`src/latexoperation.jl` but can't find anything amiss.

**Comment by gustaphe** [comment]
It appears this was solved at some point, possibly with #263
