### ISSUE TITLE
problem with symbolics derivative when using arrays

### ISSUE THREAD

**Issue by pawbz** [korsbo/Latexify.jl#271]
![image](https://github.com/korsbo/Latexify.jl/assets/11274860/76844ba5-9814-41dd-bc5e-a4d16ef10052)

**Comment by gustaphe** [comment]
What is the problem?

**Comment by pawbz** [comment]
Look at the notation, it should be d/dr1x the d in the denominator is missing

**Comment by gustaphe** [comment]
When you report this to Symbolics.jl where that latexify recipe lives, don't forget to include a description of the problem.
