### ISSUE TITLE
\text choice in recipes

### ISSUE THREAD

**Issue by ChrisRackauckas** [korsbo/Latexify.jl#317]
I'm cleaning up the Symbolics latexify output:

<img width="832" alt="Screenshot 2024-10-11 at 5 29 32 PM" src="https://github.com/user-attachments/assets/c542436a-3d5d-49a4-9f8b-271ad46fb83b">

You can see that the compound equations don't look quite right. I am fixing the `+` stuff manually, but I don't know how to make the symbol names use \text{capacitor.v} instead of just being directly written out. Also an option for \textrm would be nice.

**Comment by gustaphe** [comment]
I'm not sure I understand the problem, could you write an mwe?

**Comment by ChrisRackauckas** [comment]
```julia
using Symbolics, Latexify
@variables myvariable
latexify(myvariable)
```

produces `myvariable` and not `\text{myvariable}`

**Comment by gustaphe** [comment]
Something like 
```
diff --git a/src/latexify_recipes.jl b/src/latexify_recipes.jl
index e7c9ac54..296c8c32 100644
--- a/src/latexify_recipes.jl
+++ b/src/latexify_recipes.jl
@@ -47,12 +47,13 @@ end
 
 recipe(n) = latexify_derivatives(cleanup_exprs(_toexpr(n)))
 
-@latexrecipe function f(n::Num)
+@latexrecipe function f(n::Num; variable_style="")
     env --> :equation
     cdot --> false
     fmt --> FancyNumberFormatter(5)
 
-    return recipe(n)
+    isempty(variable_style) && return recipe(n)
+    return LaTeXString(string("\\", variable_style, "{", recipe(n), "}"))
 end
 
 @latexrecipe function f(z::Complex{Num})
```
would do it if `Num` was just a single variable. I don't know exactly how to get around the problem that
```julia
julia> set_default(; variable_style="text")
julia> @variables x y
julia> latexify(x+y)
L"\begin{equation}
\mathrm{x + y}
\end{equation}
"
```, it arises from the fact that `x + y` is a `Num`. I don't know the Symbolics internals, is there a type that encapsulates the concept of a single variable?
