### ISSUE TITLE
:head not working any more?

### ISSUE THREAD

**Issue by eirikbrandsaas** [korsbo/Latexify.jl#322]
Hi,

In 16.1 this would change the headers to capital letters
```
latexify(DataFrame(a=[1],b=[2]);env=:table,latex=false,head=["A" "B"])
L"\begin{tabular}{cc}
a & b\\
1 & 2\\
\end{tabular}
```

But now it doesnt? (I also expected it to throw an error if I did `head=["A" "B" "C"]`, but it doesnt.

**Comment by gustaphe** [comment]
Yes, https://github.com/korsbo/Latexify.jl/blob/master/ext%2FDataFramesExt.jl#L8 should have been `-->` instead of `:=`. Writing it down so I remember when I'm next at a computer.
