### ISSUE TITLE
[Suggestion] latexify unicode?

### ISSUE THREAD

**Issue by briochemc** [korsbo/Latexify.jl#35]
Is there a way to convert unicode to the corresponding LaTeX command? E.g., `latexify(α)` to actually print `$\alpha$` instead of `$α$`? (Or something similar to this idea?)

**Comment by korsbo** [comment]
I have been planning on implementing this for a while. It should not be very hard, but I have not had the time for it. 

The following would need to be done:
- Add table of unicode to latex conversions. Possibly as a const dict in its own file `const unicode_table = Dict('α'=>"\\alpha", 'β'=>"\\beta")`. This may be laborious and manual. 
- Create function to replace any characters in a string if that character exists as a key in our table. See if it is possible to do this without needing to pass through the string once for every item in our table. 
- Place call to this replacement function before the returns of `latexraw(::Symbol)` and `latexraw(::String)`. 
- Finally, write a test which ensures that all of the replacements are done correctly. 

I do not have time to do this right now, but it would be pretty straight-forward for anyone to do. So if you, or anyone else, is interested in implementing this, that would be great!

**Comment by korsbo** [comment]
I do by the way appreciate suggestions, Thanks!

**Comment by ChrisRackauckas** [comment]
I'd check how Documenter.jl does it

**Comment by briochemc** [comment]
I don't know how it's done but, at the REPL and in most editors, you can and convert LaTeX symbols into unicode, so I am guessing this means the dictionary is already there, right? (although the other way around)

**Comment by korsbo** [comment]
Thanks for the feedback and the tips. I also saw https://gitlab.com/ninjin/unicode2latex.jl a couple of days ago, which could be useful.

**Comment by isaacsas** [comment]
Now I've opened a can of worms. For unicode like: "c₁" one gets a "c\_1" as the corresponding Latex, but the latter needs the "\" dropped. This is in contrast to letter symbols. Superscripts are similar.

**Comment by korsbo** [comment]
I fixed these particular issues. I have, however, not made any efforts to find any other cases where the mapping is incorrect. Please submit issues if you find them.
