### ISSUE TITLE
Inconsistent use of braces in reaction_network generated Latex

### ISSUE THREAD

**Issue by isaacsas** [korsbo/Latexify.jl#41]
```
rn = @reaction_network gnrdtype begin
           c1, G --> G + M
           c2, M --> M + P
           c3, M --> 0
           c4, P --> 0
           c5, 2P --> P2
           c6, P2 --> 2P
           c7, P2 + G --> P2G
           c8, P2G --> P2 + G
       end c1 c2 c3 c4 c5 c6 c7 c8
print(latexify(rn, env=:chemical, mathjax=false))
```

gives
```
\begin{align}
\ce{ G &->[c1] G + M}\\
\ce{ M &->[c2] M + P}\\
\ce{ M &->[c3] \varnothing}\\
\ce{ P &->[c4] \varnothing}\\
\ce{ 2 \cdot P &<=>[{c5}][{c6}] P2}\\
\ce{ P2 + G &<=>[{c7}][{c8}] P2G}\\
\end{align}
```

which when rendered into Latex has subscripts for c1 to c4 but not c5 to c8:

![image](https://user-images.githubusercontent.com/9385167/51198415-2f6e7180-18c2-11e9-8e1a-ba0382aba38a.png)

Dropping the {} about c5 to c8 restores the subscripts.

**Comment by korsbo** [comment]
Aah, we can't have inconsistencies. I couldn't replicate this in jupyter, but in real LaTeX, I see the problem. I'll just remove the braces.

**Comment by korsbo** [comment]
I'll remove that pesky enumeration of the last, empty, line while I'm at it too.

**Comment by isaacsas** [comment]
Thanks!
