### ISSUE TITLE
noise representation from reaction networks

### ISSUE THREAD

**Issue by isaacsas** [korsbo/Latexify.jl#50]
Right now, for SDEs Latexify seems to output the coefficient of the noise term, but with an equation that it is equal to the time-derivative of the original variable. That is, for the reaction A-->0 the ODE is

dA/dt = -k*A

The SDE is

dA = -k\*A\*dt - \sqrt(k*A)*dW(t)

for a Brownian Motion, W(t). Latexify outputs for the "noise"

dA/dt = - \sqrt(k*A)

which seems a bit confusing to me. Would it be possible to add an option to output the full SDE? (I guess each equation would just get an independent dW_i(t)?)

**Comment by korsbo** [comment]
Sure, that should not be too hard. I became a parent of twins only three days ago, so I will not have time for this in a while. If you, or anyone, wish to implement this and send a PR, you should have a look in the `src/plugins/DiffEqBiological.jl`. There, there is a function which converts the reaction network to two vectors for left-hand-side and right-hand-side before passing it on to the main functions. This is where to play around.

**Comment by isaacsas** [comment]
Congrats! Thanks for the pointer on where to look. I can see where to make edits, so if I get some time maybe I'll take a pass at it.

**Comment by korsbo** [comment]
This could now be fixed pretty easily from within DiffEqBiological itself using the newly released [latex recipes](https://korsbo.github.io/Latexify.jl/latest/tutorials/recipes/).
