### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by isaacsas** [korsbo/Latexify.jl#68]
Any chance of getting an updated release that includes the `cdot` keyword? (I'd like to use this in a class. Thanks!

**Comment by korsbo** [comment]
I'll see what I can do. I have been reluctant to release this as is since I discovered that a merged PR introduces an error which i have not had time to sort out.

**Comment by isaacsas** [comment]
Ahh, that is problematic...

**Comment by korsbo** [comment]
@JuliaRegistrator register

**Comment by korsbo** [comment]
`v0.9.0` is released!

**Comment by isaacsas** [comment]
Thanks!
