### ISSUE TITLE
Latexify with DiffEqBiological chemical reactions

### ISSUE THREAD

**Issue by Msturroc** [korsbo/Latexify.jl#75]
I'm having an issue with using Latexify with chemical reactions. 

For example:

`using DiffEqBiological, Latexify

rs = @reaction_network begin
  hillr(P₃,α,K,n), ∅ --> m₁
  hillr(P₁,α,K,n), ∅ --> m₂
  hillr(P₂,α,K,n), ∅ --> m₃
  (δ,γ), m₁ ↔ ∅
  (δ,γ), m₂ ↔ ∅
  (δ,γ), m₃ ↔ ∅
  β, m₁ --> m₁ + P₁
  β, m₂ --> m₂ + P₂
  β, m₃ --> m₃ + P₃
  μ, P₁ --> ∅
  μ, P₂ --> ∅
  μ, P₃ --> ∅
end α K n δ γ β μ;

latexify(rs)
latexify(rs,env=:chemical)'

The error I get is 

ERROR: MethodError: no method matching chemical_arrows(::Tuple{Array{LaTeXString,1},Array{Union{Float64, Int64, Expr, Symbol},1}}; noise_var=:W, env=:chemical, bracket=false, noise=false, noise_only=false)
Closest candidates are:
  chemical_arrows(::DiffEqBase.AbstractReactionNetwork; expand, double_linebreak, mathjax, starred, kwargs...) at 

Using Julia 1.1 with latest release of Latexify...

**Comment by korsbo** [comment]
Thanks for reporting! 

This error was introduced with the latest release of DiffEqBiological. I'll look in to it tomorrow, but using DiffEqBiological v3.11.0 should avoid the issue until I can fix it properly.

**Comment by korsbo** [comment]
https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/159

**Comment by korsbo** [comment]
This is done but the release is still pending. Expect DiffEqBiological.jl v4.0.1 to be released within a day.

https://github.com/JuliaRegistries/General/pull/4147
