### ISSUE TITLE
Latexify outputs incorrectly when variable names contain both unicode and ascii

### ISSUE THREAD

**Issue by ChenNingCong** [korsbo/Latexify.jl#79]
[Discourse links](https://discourse.julialang.org/t/latexify-jl-outputs-incorrectly-when-variable-names-contain-both-unicode-and-ascii/30393)
It seems that if a variable contains both unicode and ascii character, latexify will product incorrect output:
```
julia> latexify("δa")
L"$\deltaa$"
```
but what I want is :`$\delta a$,` adding `_` would not help because it will change into `\delta_{a}`。

I am not sure whether this is intended.  But since it's impossible to use spaces in variable names, so I can't get around it.

**Comment by korsbo** [comment]
Thanks for reporting! This is not intended (there should be a space) and will be fixed.

**Comment by korsbo** [comment]
Is there any case in which one would want to avoid a space and instead use `{\delta}a`? This renders the same but the latex code would read better if the `\delta` is part of a longer name.
