### ISSUE TITLE
Better output for trigonometric functions?

### ISSUE THREAD

**Issue by ChenNingCong** [korsbo/Latexify.jl#82]
It seems that currently Latexify.jl doesn't handle  trigonometric function well:
```julia
julia> latexify(:(sin(x)^2))
L"$\sin\left( x \right)^{2}$"
```
But I think a more appropriate output would be`$\sin^{2}\left( x \right)$`(that is ^{2} should place on `sin` instead on `(x)`)

**Comment by korsbo** [comment]
That would be nice but I'm afraid that the implementation of this would leave a mess. Latexify uses the expression tree of an equation to determine which terms an operator should operate on. The order in which the operations are processed is given by the expression tree and in this case, one would have to deviate from that order. 

It should be possible to make a hacky fix for this but that would likely reduce stability, performance and maintainability in an unacceptable way. Alternatively, one could re-imagine the core of how latexify deals with expressions and solve this in a clean way but that would be way more work than I'm currently willing to put in. 

This is a case that I don't plan on tackling unless something else changes but I do still appreciate the suggestion, thanks!

**Comment by korsbo** [comment]
Actually, I was wrong. I have already ensured that I pass along information about what the previous operation in the expression tree was. It's still not a very straight forward fix, but it is doable.

**Comment by korsbo** [comment]
Done and released as `v0.12.2`!
