### ISSUE TITLE
Slow printf formatting

### ISSUE THREAD

**Issue by balazsmezei** [korsbo/Latexify.jl#90]
Some printf formats are very slow, especially when rendering a table with many numbers for example.
```julia
julia> @time latexify(rand(10,10), fmt="%.4g");
  6.614370 seconds (13.24 M allocations: 689.851 MiB, 1.66% gc time)
```
I think this is because of the code in `numberformatters.jl`:
```julia
s = @eval @sprintf $(f.fmt) $x
```
The issue is that the eval is called for each number $x. But the format is the same every time so this is unnecessary.  If we generate the formatter in advance, things are much better.
```julia
julia> fmt="%.4g"
"%.4g"

julia> f = @eval x -> @sprintf($fmt, x);

julia> @time latexify(rand(10,10), fmt=f);
  0.225207 seconds (378.32 k allocations: 19.770 MiB)
```
If we use f again, it will be even faster as f is compiled(?) the first the it is called.

It would be nice if this could be implemented somehow and so that the above workaround is not needed. I'm not sure how it should be done, hence I've made this issue instead of a PR.

**Comment by korsbo** [comment]
Thanks for reporting, I had never noticed this myself. I have fixed the issue and will release it shortly.
