### ISSUE TITLE
Usage in PyPlot

### ISSUE THREAD

**Issue by janrpeters** [korsbo/Latexify.jl#99]
I would like to use latexify with PyPlot. The following code works for me

`
rcParams = PyDict(matplotlib["rcParams"])
rcParams["text.usetex"] = true;
rcParams["text.latex.preamble"] = raw"\usepackage{{amsmath}}";
ax.text(-0.75,-0.75,L"$\left[\begin{array}{cc}0.0 & -0.2 \\0.0 & -0.2 \\\end{array} \right]$");=
`

but I would like to use latexify instead in

`
A = [0,-0.2; 0, +0.2];
ax.text(-0.75,-0.75,latexify(A))`

instead. But I only manage to get 

`
A_new = replace(replace(replace(latexify(A), 
            "\\begin{equation}" => L"$"),
            "\\end{equation}" => L"$"),
            "\n" => "")
ax.text(-0.25,-0.75,A_new)`

to work while for `latexify(A; env=:inline)`, I get 

`LaTeXString[L"$0.0$" L"$-0.2$"; L"$0.2$" L"$0.0$"]`

which cannot be used by text. If you had an env to directly return the right format ... that would be very cool. Thanks for considering...

**Comment by korsbo** [comment]
Hi,
I think that this is part of a deeper problem regarding output configurability. What you seem to need is essentially the ability to specify that you want some `InlineEnv` to surround `SquareBracket` which surrounds `ArrayEnv`. Switching from `env = :something` to a proper dispatch system could facilitate such composability. I think that it could be a great improvement and I'd be happy to do this but it will have to wait until I have more time (submitting PhD in September).

**Comment by janrpeters** [comment]
Good luck with the Ph.D. … and keep up your fantastic Julia work!

**Comment by korsbo** [comment]
This was enabled in 0.15.0. `latexify(A; env=:inline)` should now do the trick.
